version: 2.1
orbs:
  sixrs-gke: sixriversystems/sixrs-gke@0.2.1
jobs:
  build-publish-deploy:
    docker:
      - image: circleci/node:10
        environment:
          - CLUSTER: srs-internal
    steps:
      - checkout
      - setup_remote_docker
      - sixrs-gke/run-release
      - sixrs-gke/docker-login
      - attach_workspace:
        at: ./
      - sixrs-gke/build-and-publish
      - sixrs-gke/deploy:
          namespace: techops
          deployment: safetybot
          container: safetybot
          image: safetybot
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-publish-deploy:
          context: 6rs-circle